---
language: node_js
node_js:
  - "0.10"
addons:
  postgresql: "9.3"
before_script:
  - psql -c 'create database notethevotes;' -U postgres
env: 'DATABASE_URL="postgres://postgres@localhost/notethevotes"'
script: "npm run travis-ci"
